/**
 * ChefMii — AI-Generated Image Registry
 * All images generated by Gemini. Paths are served from /public/images/
 * Copy the generated .png files from the brain directory to public/images/
 */

export const CHEF_IMAGES: Record<string, string> = {
    'chef-marco-rossi': '/images/chefs/chef_marco_rossi.png',
    'chef-aisha-okafor': '/images/chefs/chef_aisha_okafor.png',
    'chef-yuki-tanaka': '/images/chefs/chef_yuki_tanaka.png',
    'chef-pierre-dubois': '/images/chefs/chef_pierre_dubois.png',
    'chef-sofia-mendez': '/images/chefs/chef_sofia_mendez.png',
    'chef-meera-patel': '/images/chefs/chef_meera_patel.png',
}

export const MARKETPLACE_IMAGES: Record<string, string> = {
    'sicilian-olive-oil': '/images/marketplace/marketplace_olive_oil.png',
    'jollof-spice-blend': '/images/marketplace/marketplace_jollof_spice.png',
    'matcha-ceremonial': '/images/marketplace/marketplace_matcha.png',
    'black-garlic': '/images/marketplace/marketplace_black_garlic.png',
    'smoked-sea-salt': '/images/marketplace/marketplace_sea_salt.png',
    'dark-chocolate': '/images/marketplace/marketplace_chocolate.png',
    'san-marzano-tomatoes': '/images/marketplace/marketplace_san_marzano.png',
    'truffle-oil': '/images/marketplace/marketplace_truffle_oil.png',
}

export const EVENT_IMAGES: Record<string, string> = {
    'intimate-dinner': '/images/events/event_intimate_dinner.png',
    'corporate-dining': '/images/events/event_corporate_dining.png',
    'wedding-feast': '/images/events/event_wedding_feast.png',
    'birthday': '/images/events/event_birthday_celebration.png',
}

export const ACADEMY_IMAGES: Record<string, string> = {
    'pasta-masterclass': '/images/academy/academy_pasta_masterclass.png',
    'sushi-masterclass': '/images/academy/academy_sushi_masterclass.png',
    'pastry-course': '/images/academy/academy_pastry_course.png',
    'wine-pairing': '/images/academy/academy_wine_pairing.png',
}

export const KIDS_IMAGES: Record<string, string> = {
    'fruit-salad': '/images/kids/kids_fruit_salad.png',
    'pancakes': '/images/kids/kids_pancakes.png',
    'veggie-skewers': '/images/kids/kids_veggie_skewers.png',
    'mini-pizza': '/images/kids/kids_mini_pizza.png',
}

/** Fallback: high-quality Unsplash URLs used until images are copied to public/ */
export const CHEF_FALLBACKS: Record<string, string> = {
    'chef-marco-rossi': 'https://images.unsplash.com/photo-1577219491135-ce391730fb2c?w=400&q=80',
    'chef-aisha-okafor': 'https://images.unsplash.com/photo-1607631568010-a87245c0daf8?w=400&q=80',
    'chef-yuki-tanaka': 'https://images.unsplash.com/photo-1583394293214-d4e8a3a959b1?w=400&q=80',
    'chef-pierre-dubois': 'https://images.unsplash.com/photo-1600565193348-f74bd3960303?w=400&q=80',
    'chef-sofia-mendez': 'https://images.unsplash.com/photo-1581299894007-aaa50297cf16?w=400&q=80',
    'chef-meera-patel': 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=400&q=80',
}

export const MARKETPLACE_FALLBACKS: Record<string, string> = {
    'sicilian-olive-oil': 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400&q=80',
    'jollof-spice-blend': 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&q=80',
    'matcha-ceremonial': 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&q=80',
    'black-garlic': 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=400&q=80',
    'smoked-sea-salt': 'https://images.unsplash.com/photo-1584255014406-2a68ea38e48c?w=400&q=80',
    'dark-chocolate': 'https://images.unsplash.com/photo-1548907040-4baa42d10919?w=400&q=80',
    'san-marzano-tomatoes': 'https://images.unsplash.com/photo-1546470427-0d4a3f5f3c3b?w=400&q=80',
    'truffle-oil': 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400&q=80',
}

export const EVENT_FALLBACKS: Record<string, string> = {
    'intimate-dinner': 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&q=80',
    'corporate-dining': 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=600&q=80',
    'wedding-feast': 'https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=600&q=80',
    'birthday': 'https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?w=600&q=80',
}

export const ACADEMY_FALLBACKS: Record<string, string> = {
    'pasta-masterclass': 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&q=80',
    'sushi-masterclass': 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=600&q=80',
    'pastry-course': 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&q=80',
    'wine-pairing': 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=600&q=80',
}

export const KIDS_FALLBACKS: Record<string, string> = {
    'fruit-salad': 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&q=80',
    'pancakes': 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=400&q=80',
    'veggie-skewers': 'https://images.unsplash.com/photo-1529059997568-3d847b1154f0?w=400&q=80',
    'mini-pizza': 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400&q=80',
}
